apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fmil41qfu-python 
  janus-idp.io/tekton: fmil41qfu-python
  backstage.io/kubernetes-id: fmil41qfu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fmil41qfu-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  