apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fmil41qfu-python-gitops
  description: This is GitOps manifest for fmil41qfu-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: fmil41qfu-python
    backstage.io/kubernetes-id: fmil41qfu-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fmil41qfu-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fmil41qfu-python
