apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fmil41qfu-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fmil41qfu-python 
  name: fmil41qfu-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fmil41qfu-python 
